# -*- coding: utf-8 -*-
"""ContextGEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Balachandar-Ganesan/GraphRAG/blob/main/ContextGEM.ipynb
"""

!pip install contextgem

from google.colab import userdata
# Access the API key stored in Colab Secrets
openai_api_key = userdata.get('OPENAI_API_KEY')

# Quick Start Example - Extracting an aspect with sub-aspects

import os

from contextgem import Aspect, Document, DocumentLLM

# Sample document (content shortened for brevity)
contract_text = """
1. What are the constitutional options before a Governor when a Bill is presented to him under Article 200 of the Constitution of India?
2. Is the Governor bound by the aid & advice tendered by the Council of Ministers while exercising all the options available with him when a Bill is presented before him under Article 200 of the Constitution of India?
3. Is the exercise of constitutional discretion by the Governor under Article 200 of the Constitution of India justiciable?
4. Is Article 361 of the Constitution of India an absolute bar to the judicial review in relation to the actions of a Governor under Article 200 of the Constitution of India?
5. In the absence of a constitutionally prescribed time limit, and the manner of exercise of powers by the Governor, can timelines be imposed and the manner of exercise be prescribed through judicial orders for the exercise of all powers under Article 200 of the Constitution of India by the Governor?
6. Is the exercise of constitutional discretion by the President under Article 201 of the Constitution of India justiciable?
7. In the absence of a constitutionally prescribed timeline and the manner of exercise of powers by the President, can timelines be imposed and the manner of exercise be prescribed through judicial orders for the exercise of discretion by the President under Article 201 of the Constitution of India?
8. In light of the constitutional scheme governing the powers of the President, is the President required to seek advice of the Supreme Court by way of a reference under Article 143 of the Constitution of India and take the opinion of the Supreme Court when the Governor reserves a Bill for the President's assent or otherwise?
9. Are the decisions of the Governor and the President under Article 200 and Article 201 of the Constitution of India, respectively, justiciable at a stage anterior into the law coming into force? Is it permissible for the Courts to undertake judicial adjudication over the contents of a Bill, in any manner, before it becomes law?
10. Can the exercise of constitutional powers and the orders of/by the President / Governor be substituted in any manner under Article 142 of the Constitution of India?
11. Is a law made by the State legislature a law in force without the assent of the Governor granted under Article 200 of the Constitution of India?
12. In view of the proviso to Article 145(3) of the Constitution of India, is it not mandatory for any bench of this Hon'ble Court to first decide as to whether the question involved in the proceedings before it is of such a nature which involves substantial questions of law as to the interpretation of constitution and to refer it to a bench of minimum five Judges?
13. Do the powers of the Supreme Court under Article 142 of the Constitution of India limited to matters of procedural law or Article 142 of the Constitution of India extends to issuing directions /passing orders which are contrary to or inconsistent with existing substantive or procedural provisions of the Constitution or law in force?
14. Does the Constitution bar any other jurisdiction of the Supreme Court to resolve disputes between the Union Government and the State Governments except by way of a suit under Article 131 of the Constitution of India?
"""

doc = Document(raw_text=contract_text)

# Define Article143 aspect with practical sub-aspects
Article143_aspect = Aspect(
    name="Constitution",
    description="Provisions related to body",
    aspects=[  # assign sub-aspects (optional)
        Aspect(
            name="State Government Rights",
            description="Conditions under which State Government has maximum rights",
        ),
        Aspect(
            name="'President's Rights",
            description="Conditions under which President has maximum rights",
        ),
        Aspect(
            name="Supreme Court Rights",
            description="Conditions under which Supreme Court has maximum rights",
        ),
        Aspect(
            name="Governor Rights",
            description="Conditions under which Governor has maximum rights"
        ),
    ],
)

# Add the aspect to the document. Sub-aspects are added with the parent aspect.
doc.add_aspects([Article143_aspect])
# (add more aspects to the document, if needed)

# Create an LLM for extraction
llm = DocumentLLM(
    model="openai/gpt-4o-mini",  # or any other LLM from e.g. Anthropic, etc.
    api_key=openai_api_key,  # your API key of the LLM provider
)

# Extract all information from the document
doc = llm.extract_all(doc)

# Get results with references in the document object
print("\n Constitution aspect:\n")
Article143_aspect = doc.get_aspect_by_name("Constitution")
for sub_aspect in Article143_aspect.aspects:
    print(sub_aspect.name)
    for item in sub_aspect.extracted_items:
        print(item.value)
    print("\n")