# -*- coding: utf-8 -*-
"""GenAIMistralGemma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6BFw87BmKoLQA0_vRepqHsNiSVvfFgv
"""

!pip install llama_index.llms.mistralai
!pip install llama-index-core
!pip install llama-index-llms-openai
!pip install llama-index-llms-replicate
!pip install llama-index-embeddings-huggingface

import os

os.environ["MISTRAL_API_KEY"] = ""

from llama_index.llms.mistralai import MistralAI

llm = MistralAI(model="codestral-latest", temperature=0.1)

from llama_index.core.llms import ChatMessage

def getCode(strContent):
  messages = [ChatMessage(role="user", content=strContent)]

  response = llm.chat(messages)

  return response

strContent ="""
I have a table in SQL.
It has columns Runs,Innings and MatchDate.
Write a query to get runs scored during First Innings every year
"""
print(getCode(strContent))

strContent ="""
Would like to get more details on Laywer Ravishankar in Anna Nagar. Please consolidate public comments
and provide summary as well."
"""
print(getCode(strContent))

strContent ="""
Write a Code in Python for Email Validation
using regex and Decorators
"""
print(getCode(strContent))

strContent ="""
I have a table in PowerBI.
It has two columns Price and SellDate.
How to compute Aroon Indicator for Price column
"""
print(getCode(strContent))

strContent ="""
I have a table in Qlikview.
It has two columns Price and SellDate.
How to compute YTD for the price column
"""
print(getCode(strContent))

strContent ="""
I have the data of local train movement in Mumbai with traincode,starttime,startlocation,endlocation.
Want to create animation to display passenger movement using map control
Explain steps needed
"""
print(getCode(strContent))